name: Ping Vercel Endpoint
on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call FastAPI endpoint
        run: curl -s https://e-com-data.vercel.app/run-db-update/run-db-update
